// ReportCenter.jsx — FinGenie Report Center
import { useState } from 'react';
import ExportSuite from './ExportSuite';

const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';

const AI_REPORT_FORMATS = [
  { id: 'executive', icon: '🏛️', label: 'Executive Brief',  desc: 'Concise strategic summary for C-suite' },
  { id: 'investor',  icon: '📈', label: 'Investor Memo',     desc: 'Growth narrative & opportunity framing' },
  { id: 'audit',     icon: '🔍', label: 'Internal Audit',    desc: 'Detailed compliance & risk analysis' },
  { id: 'board',     icon: '🏢', label: 'Board Update',      desc: 'Governance-focused balanced overview' },
  { id: 'startup',   icon: '🚀', label: 'Pitch Narrative',   desc: 'Fundraising-ready energetic framing' },
  { id: 'academic',  icon: '🎓', label: 'Research Paper',    desc: 'Structured, methodology-driven analysis' },
];

function mdToHtml(md) {
  if (!md) return '';
  return md
    .replace(/^## (.+)$/gm,  '<h2 class="ai-report-h2">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 class="ai-report-h3">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g,    '<em>$1</em>')
    .replace(/^[•\-] (.+)$/gm, '<li>$1</li>')
    .replace(/^(\d+)\. (.+)$/gm, '<li><span class="ai-report-num">$1</span> $2</li>')
    .replace(/(<li>[\s\S]+?<\/li>)(?=\n<li>|\n\n|$)/g, '<ul>$&</ul>')
    .replace(/<\/ul>\n<ul>/g, '')
    .replace(/^(?!<[hul])(.+)$/gm, '<p>$1</p>')
    .replace(/<p>\s*<\/p>/g, '');
}

function buildReportHTML({ selectedFmt, stmtType, now, report }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>FinGenie — ${selectedFmt?.label}</title>
<style>
  body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 800px;
         margin: 60px auto; padding: 0 40px; color: #1a1a2e; line-height: 1.7; }
  .cover { border-bottom: 3px solid hsl(220, 90%, 55%); padding-bottom: 32px; margin-bottom: 40px; }
  .cover-eyebrow { font-size: 11px; letter-spacing: 2px; text-transform: uppercase;
                   color: hsl(220, 90%, 55%); margin-bottom: 8px; }
  .cover-title { font-size: 32px; font-weight: 700; margin: 0 0 8px; }
  .cover-meta  { font-size: 13px; color: #6b7280; }
  h2 { font-size: 18px; font-weight: 600; color: hsl(220, 90%, 45%);
       border-bottom: 1px solid hsl(220, 100%, 93%); padding-bottom: 6px; margin-top: 32px; }
  h3 { font-size: 14px; font-weight: 600; color: hsl(220, 40%, 15%); margin-top: 24px;
       text-transform: uppercase; letter-spacing: .05em; }
  p  { margin: 12px 0; color: #374151; }
  ul { padding-left: 20px; } li { margin: 6px 0; color: #374151; }
  em { color: #6b7280; }
  .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #e5e7eb;
            font-size: 11px; color: #9ca3af; }
</style>
</head>
<body>
<div class="cover">
  <div class="cover-eyebrow">FinGenie AI · ${stmtType}</div>
  <div class="cover-title">${selectedFmt?.label}</div>
  <div class="cover-meta">Generated on ${now} · Powered by Groq Llama 3.3</div>
</div>
${mdToHtml(report)}
<div class="footer">
  Generated by FinGenie AI · Powered by Groq Llama 3.3 · For informational purposes only.
</div>
</body>
</html>`;
}

function printViaIframe(html) {
  const iframe = document.createElement('iframe');
  iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:0;height:0;border:none;visibility:hidden;';
  document.body.appendChild(iframe);
  const doc = iframe.contentDocument || iframe.contentWindow.document;
  doc.open(); doc.write(html); doc.close();
  setTimeout(() => {
    iframe.contentWindow.focus();
    iframe.contentWindow.print();
    setTimeout(() => { if (document.body.contains(iframe)) document.body.removeChild(iframe); }, 3000);
  }, 500);
}

// ── Analyzer-style header ─────────────────────────────────────────────────────
function ReportCenterHeader({ analysisResult }) {
  const kpis        = analysisResult?.kpis          || [];
  const risks       = analysisResult?.risks         || [];
  const recs        = analysisResult?.recommendations || [];
  const rawData     = analysisResult?.raw_data       || [];
  const stmtType    = analysisResult?.statement_type || 'FG-24';
  const parsingMode = analysisResult?.parsing_mode   || 'standard';

  const now = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  return (
    <div className="fade-in slide-up">
      <div
        className="report-header"
        style={{ borderBottom: '1px solid var(--border-light)', paddingBottom: '40px', marginBottom: '48px' }}
      >
        <div className="sub-label" style={{ color: 'var(--accent-blue)', marginBottom: '8px', fontSize: '13px' }}>
          REPORT CENTER / {now.toUpperCase()}
        </div>
        <h1 className="big-title" style={{ fontSize: '40px' }}>
          Multi-Format Report<br />
          <span style={{ color: 'var(--accent-emerald)' }}>Generation Suite.</span>
        </h1>

        <div
          className="meta-bar"
          style={{ marginTop: '24px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px' }}
        >
          <span style={{ fontSize: '14px', fontWeight: 700, color: 'var(--text-secondary)', letterSpacing: '0.03em' }}>
            STATEMENT: {stmtType.toUpperCase()}
          </span>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'center', flexWrap: 'wrap' }}>
            <div style={{ display: 'flex', gap: '8px', alignItems: 'center', fontSize: '13px', fontWeight: 600 }}>
              <div style={{ width: '8px', height: '8px', background: 'var(--accent-emerald)', borderRadius: '50%' }} />
              <span>Parsing Mode: {parsingMode}</span>
            </div>
            <div style={{ display: 'flex', gap: '16px' }}>
              {[
                { label: 'KPIs',  val: kpis.length },
                { label: 'Risks', val: risks.length },
                { label: 'Recs',  val: recs.length },
                { label: 'Rows',  val: rawData.length },
              ].map(({ label, val }) => (
                <div key={label} style={{ textAlign: 'center' }}>
                  <div style={{ fontSize: '18px', fontWeight: 900, color: 'var(--text-primary)', fontFamily: 'Outfit', lineHeight: 1 }}>{val}</div>
                  <div style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase', color: 'var(--text-muted)', letterSpacing: '0.05em' }}>{label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── AI Report Generator ───────────────────────────────────────────────────────
function AIReportGenerator({ analysisResult }) {
  const [format,     setFormat]     = useState('executive');
  const [report,     setReport]     = useState('');
  const [wordCount,  setWordCount]  = useState(0);
  const [loading,    setLoading]    = useState(false);
  const [error,      setError]      = useState('');
  const [downloaded, setDownloaded] = useState(false);
  const [pdfSaved,   setPdfSaved]   = useState(false);

  const selectedFmt = AI_REPORT_FORMATS.find(f => f.id === format);

  const generate = async () => {
    setLoading(true); setError(''); setReport(''); setWordCount(0);
    try {
      const res = await fetch(`${API_BASE}/api/report/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          format_id:       format,
          raw_data:        analysisResult?.raw_data        || [],
          column_headers:  analysisResult?.column_headers  || [],
          statement_type:  analysisResult?.statement_type  || 'Financial Statement',
          summary:         analysisResult?.summary         || '',
          kpis:            analysisResult?.kpis            || [],
          risks:           analysisResult?.risks           || [],
          recommendations: analysisResult?.recommendations || [],
          parsing_mode:    analysisResult?.parsing_mode    || 'standard',
        }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err?.detail || `Server error ${res.status}`);
      }
      const data = await res.json();
      setReport(data.report_markdown);
      setWordCount(data.word_count);
    } catch (err) {
      setError('Failed to generate report: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const getHtmlPayload = () => {
    const stmtType = analysisResult?.statement_type || 'report';
    const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return buildReportHTML({ selectedFmt, stmtType, now, report });
  };

  const downloadHTML = () => {
    const html = getHtmlPayload();
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = `fingenie-${format}-report.html`;
    a.click(); URL.revokeObjectURL(url);
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 3000);
  };

  const downloadPDF = () => {
    printViaIframe(getHtmlPayload());
    setPdfSaved(true);
    setTimeout(() => setPdfSaved(false), 4000);
  };

  return (
    <div className="ai-report-generator">
      <div className="ai-format-section">
        <div className="section-label">Choose report format</div>
        <div className="ai-format-grid">
          {AI_REPORT_FORMATS.map(f => (
            <div
              key={f.id}
              className={`ai-format-card ${format === f.id ? 'selected' : ''}`}
              onClick={() => { setFormat(f.id); setReport(''); setError(''); }}
            >
              <span className="aif-icon">{f.icon}</span>
              <div className="aif-label">{f.label}</div>
              <div className="aif-desc">{f.desc}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="ai-data-chips">
        <span className="ai-chip">📊 {analysisResult?.kpis?.length || 0} KPIs</span>
        <span className="ai-chip">⚠️ {analysisResult?.risks?.length || 0} Risks</span>
        <span className="ai-chip">💡 {analysisResult?.recommendations?.length || 0} Recs</span>
        <span className="ai-chip">📋 {analysisResult?.raw_data?.length || 0} Data rows</span>
        <span className="ai-chip ai-chip-type">🏷️ {analysisResult?.statement_type || 'Unknown type'}</span>
      </div>

      <button
        className={`ai-generate-btn ${loading ? 'ai-generating' : ''}`}
        onClick={generate}
        disabled={loading}
      >
        {loading
          ? <><span className="ai-pulse-dot" /> Synthesising {selectedFmt?.label} via Groq…</>
          : <>{selectedFmt?.icon} Generate {selectedFmt?.label} with Groq AI</>
        }
      </button>

      {error && <div className="ai-error-block">⚠️ {error}</div>}

      {report && (
        <div className="ai-report-output">
          <div className="ai-report-toolbar">
            <div className="ai-report-meta">
              <span className="ai-report-badge">{selectedFmt?.icon} {selectedFmt?.label}</span>
              <span className="ai-report-timestamp">
                {wordCount} words ·{' '}
                {new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
              </span>
            </div>
            <div className="ai-toolbar-actions">
              <button className="ai-tool-btn" onClick={downloadHTML}>
                {downloaded ? '✅ Saved!' : '🌐 Download HTML'}
              </button>
              <button className="ai-tool-btn ai-tool-btn-primary" onClick={downloadPDF}>
                {pdfSaved ? '✅ Print dialog opened!' : '📄 Download PDF'}
              </button>
            </div>
          </div>
          <div className="ai-report-content" dangerouslySetInnerHTML={{ __html: mdToHtml(report) }} />
        </div>
      )}
    </div>
  );
}

// ── Main export ───────────────────────────────────────────────────────────────
export default function ReportCenter({ analysisResult }) {
  const [activeLayer, setActiveLayer] = useState('ai');

  if (!analysisResult) return null;

  const layers = [
    { id: 'ai',     icon: '🤖', title: 'AI Report'    },
    { id: 'export', icon: '📦', title: 'Export Suite'  },
  ];

  return (
    <section className="card report-center-card fade-in" id="report-center-section">

      <ReportCenterHeader analysisResult={analysisResult} />

      <div style={{ marginBottom: '24px' }}>
        <div className="sub-label" style={{ marginBottom: '16px' }}>REPORT GENERATION TOOLS</div>

        {/* Layer nav tabs */}
        <div className="layers-nav">
          {layers.map(layer => (
            <button
              key={layer.id}
              className={`layer-tab ${activeLayer === layer.id ? 'active' : ''} ${layer.id === 'ai' ? 'layer-tab-ai' : ''}`}
              onClick={() => setActiveLayer(layer.id)}
            >
              <span className="lt-icon">{layer.icon}</span>
              <div className="lt-title">{layer.title}</div>
            </button>
          ))}
        </div>
      </div>

      {/* Tab panels */}
      <div className="layer-panels">
        {activeLayer === 'ai'     && <AIReportGenerator analysisResult={analysisResult} />}
        {activeLayer === 'export' && <ExportSuite       analysisResult={analysisResult} />}
      </div>
    </section>
  );
}
