// @ts-nocheck
function stryNS_9fa48() {
  var g = typeof globalThis === 'object' && globalThis && globalThis.Math === Math && globalThis || new Function("return this")();
  var ns = g.__stryker__ || (g.__stryker__ = {});
  if (ns.activeMutant === undefined && g.process && g.process.env && g.process.env.__STRYKER_ACTIVE_MUTANT__) {
    ns.activeMutant = g.process.env.__STRYKER_ACTIVE_MUTANT__;
  }
  function retrieveNS() {
    return ns;
  }
  stryNS_9fa48 = retrieveNS;
  return retrieveNS();
}
stryNS_9fa48();
function stryCov_9fa48() {
  var ns = stryNS_9fa48();
  var cov = ns.mutantCoverage || (ns.mutantCoverage = {
    static: {},
    perTest: {}
  });
  function cover() {
    var c = cov.static;
    if (ns.currentTestId) {
      c = cov.perTest[ns.currentTestId] = cov.perTest[ns.currentTestId] || {};
    }
    var a = arguments;
    for (var i = 0; i < a.length; i++) {
      c[a[i]] = (c[a[i]] || 0) + 1;
    }
  }
  stryCov_9fa48 = cover;
  cover.apply(null, arguments);
}
function stryMutAct_9fa48(id) {
  var ns = stryNS_9fa48();
  function isActive(id) {
    if (ns.activeMutant === id) {
      if (ns.hitCount !== void 0 && ++ns.hitCount > ns.hitLimit) {
        throw new Error('Stryker: Hit count limit reached (' + ns.hitCount + ')');
      }
      return true;
    }
    return false;
  }
  stryMutAct_9fa48 = isActive;
  return isActive(id);
}
import React from 'react';
import { Scale, AlertTriangle } from 'lucide-react';
export default function Terms() {
  if (stryMutAct_9fa48("1519")) {
    {}
  } else {
    stryCov_9fa48("1519");
    return <div className="fade-in slide-up px-6 md:px-12 py-16" style={stryMutAct_9fa48("1520") ? {} : (stryCov_9fa48("1520"), {
      maxWidth: stryMutAct_9fa48("1521") ? "" : (stryCov_9fa48("1521"), '1000px'),
      margin: stryMutAct_9fa48("1522") ? "" : (stryCov_9fa48("1522"), '0 auto')
    })}>
      <div className="sub-label">Legal Framework</div>
      <h1 className="hero-title mb-md">Terms of <br /><span className="text-accent">Operation.</span></h1>
      
      <div className="card-light" style={stryMutAct_9fa48("1523") ? {} : (stryCov_9fa48("1523"), {
        padding: stryMutAct_9fa48("1524") ? "" : (stryCov_9fa48("1524"), '40px'),
        borderRadius: stryMutAct_9fa48("1525") ? "" : (stryCov_9fa48("1525"), 'var(--radius-xl)')
      })}>
        <div className="d-flex flex-column gap-5">
           <div className="d-flex gap-4">
              <div style={stryMutAct_9fa48("1526") ? {} : (stryCov_9fa48("1526"), {
              background: stryMutAct_9fa48("1527") ? "" : (stryCov_9fa48("1527"), 'var(--bg-blue-light)'),
              padding: stryMutAct_9fa48("1528") ? "" : (stryCov_9fa48("1528"), '12px'),
              borderRadius: stryMutAct_9fa48("1529") ? "" : (stryCov_9fa48("1529"), '12px'),
              height: stryMutAct_9fa48("1530") ? "" : (stryCov_9fa48("1530"), 'fit-content')
            })}>
                <Scale className="text-accent" size={24} />
              </div>
              <div>
                 <h2 className="text-primary font-bold mb-xs" style={stryMutAct_9fa48("1531") ? {} : (stryCov_9fa48("1531"), {
                fontSize: stryMutAct_9fa48("1532") ? "" : (stryCov_9fa48("1532"), '18px')
              })}>Institutional Usage</h2>
                 <p className="text-secondary" style={stryMutAct_9fa48("1533") ? {} : (stryCov_9fa48("1533"), {
                fontSize: stryMutAct_9fa48("1534") ? "" : (stryCov_9fa48("1534"), '14px'),
                lineHeight: 1.7
              })}>
                    FinGenie is provided as a financial utility for informational purposes. Analysis is generated by AI models and should be verified by certified professionals.
                 </p>
              </div>
           </div>

           <div className="d-flex gap-4">
              <div style={stryMutAct_9fa48("1535") ? {} : (stryCov_9fa48("1535"), {
              background: stryMutAct_9fa48("1536") ? "" : (stryCov_9fa48("1536"), 'rgba(235, 29, 72, 0.05)'),
              padding: stryMutAct_9fa48("1537") ? "" : (stryCov_9fa48("1537"), '12px'),
              borderRadius: stryMutAct_9fa48("1538") ? "" : (stryCov_9fa48("1538"), '12px'),
              height: stryMutAct_9fa48("1539") ? "" : (stryCov_9fa48("1539"), 'fit-content')
            })}>
                <AlertTriangle className="text-rose" size={24} style={stryMutAct_9fa48("1540") ? {} : (stryCov_9fa48("1540"), {
                color: stryMutAct_9fa48("1541") ? "" : (stryCov_9fa48("1541"), 'var(--accent-rose)')
              })} />
              </div>
              <div>
                 <h2 className="text-primary font-bold mb-xs" style={stryMutAct_9fa48("1542") ? {} : (stryCov_9fa48("1542"), {
                fontSize: stryMutAct_9fa48("1543") ? "" : (stryCov_9fa48("1543"), '18px')
              })}>No Financial Advice</h2>
                 <p className="text-secondary" style={stryMutAct_9fa48("1544") ? {} : (stryCov_9fa48("1544"), {
                fontSize: stryMutAct_9fa48("1545") ? "" : (stryCov_9fa48("1545"), '14px'),
                lineHeight: 1.7
              })}>
                    Output from FinGenie does not constitute financial, investment, or legal advice. FINGENIE FINANCIAL UTILITIES assumes no liability for decisions made based on AI output.
                 </p>
              </div>
           </div>
        </div>
      </div>
    </div>;
  }
}