// @ts-nocheck
import React from 'react';
import { Scale, AlertTriangle } from 'lucide-react';

export default function Terms() {
  return (
    <div className="fade-in slide-up px-6 md:px-12 py-16" style={{maxWidth: '1000px', margin: '0 auto'}}>
      <div className="sub-label">Legal Framework</div>
      <h1 className="hero-title mb-md">Terms of <br/><span className="text-accent">Operation.</span></h1>
      
      <div className="card-light" style={{padding: '40px', borderRadius: 'var(--radius-xl)'}}>
        <div className="d-flex flex-column gap-5">
           <div className="d-flex gap-4">
              <div style={{ background: 'var(--bg-blue-light)', padding: '12px', borderRadius: '12px', height: 'fit-content' }}>
                <Scale className="text-accent" size={24} />
              </div>
              <div>
                 <h2 className="text-primary font-bold mb-xs" style={{fontSize: '18px'}}>Institutional Usage</h2>
                 <p className="text-secondary" style={{fontSize: '14px', lineHeight: 1.7}}>
                    FinGenie is provided as a financial utility for informational purposes. Analysis is generated by AI models and should be verified by certified professionals.
                 </p>
              </div>
           </div>

           <div className="d-flex gap-4">
              <div style={{ background: 'rgba(235, 29, 72, 0.05)', padding: '12px', borderRadius: '12px', height: 'fit-content' }}>
                <AlertTriangle className="text-rose" size={24} style={{ color: 'var(--accent-rose)' }} />
              </div>
              <div>
                 <h2 className="text-primary font-bold mb-xs" style={{fontSize: '18px'}}>No Financial Advice</h2>
                 <p className="text-secondary" style={{fontSize: '14px', lineHeight: 1.7}}>
                    Output from FinGenie does not constitute financial, investment, or legal advice. FINGENIE FINANCIAL UTILITIES assumes no liability for decisions made based on AI output.
                 </p>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}
