// @ts-nocheck
function stryNS_9fa48() {
  var g = typeof globalThis === 'object' && globalThis && globalThis.Math === Math && globalThis || new Function("return this")();
  var ns = g.__stryker__ || (g.__stryker__ = {});
  if (ns.activeMutant === undefined && g.process && g.process.env && g.process.env.__STRYKER_ACTIVE_MUTANT__) {
    ns.activeMutant = g.process.env.__STRYKER_ACTIVE_MUTANT__;
  }
  function retrieveNS() {
    return ns;
  }
  stryNS_9fa48 = retrieveNS;
  return retrieveNS();
}
stryNS_9fa48();
function stryCov_9fa48() {
  var ns = stryNS_9fa48();
  var cov = ns.mutantCoverage || (ns.mutantCoverage = {
    static: {},
    perTest: {}
  });
  function cover() {
    var c = cov.static;
    if (ns.currentTestId) {
      c = cov.perTest[ns.currentTestId] = cov.perTest[ns.currentTestId] || {};
    }
    var a = arguments;
    for (var i = 0; i < a.length; i++) {
      c[a[i]] = (c[a[i]] || 0) + 1;
    }
  }
  stryCov_9fa48 = cover;
  cover.apply(null, arguments);
}
function stryMutAct_9fa48(id) {
  var ns = stryNS_9fa48();
  function isActive(id) {
    if (ns.activeMutant === id) {
      if (ns.hitCount !== void 0 && ++ns.hitCount > ns.hitLimit) {
        throw new Error('Stryker: Hit count limit reached (' + ns.hitCount + ')');
      }
      return true;
    }
    return false;
  }
  stryMutAct_9fa48 = isActive;
  return isActive(id);
}
import React from 'react';
import { Scale, AlertTriangle } from 'lucide-react';
export default function Terms() {
  if (stryMutAct_9fa48("1742")) {
    {}
  } else {
    stryCov_9fa48("1742");
    return <div className="fade-in slide-up px-6 md:px-12 py-16" style={stryMutAct_9fa48("1743") ? {} : (stryCov_9fa48("1743"), {
      maxWidth: stryMutAct_9fa48("1744") ? "" : (stryCov_9fa48("1744"), '1000px'),
      margin: stryMutAct_9fa48("1745") ? "" : (stryCov_9fa48("1745"), '0 auto')
    })}>
      <div className="sub-label">Legal Framework</div>
      <h1 className="hero-title mb-md">Terms of <br /><span className="text-accent">Operation.</span></h1>
      
      <div className="card-light" style={stryMutAct_9fa48("1746") ? {} : (stryCov_9fa48("1746"), {
        padding: stryMutAct_9fa48("1747") ? "" : (stryCov_9fa48("1747"), '40px'),
        borderRadius: stryMutAct_9fa48("1748") ? "" : (stryCov_9fa48("1748"), 'var(--radius-xl)')
      })}>
        <div className="d-flex flex-column gap-5">
           <div className="d-flex gap-4">
              <div style={stryMutAct_9fa48("1749") ? {} : (stryCov_9fa48("1749"), {
              background: stryMutAct_9fa48("1750") ? "" : (stryCov_9fa48("1750"), 'var(--bg-blue-light)'),
              padding: stryMutAct_9fa48("1751") ? "" : (stryCov_9fa48("1751"), '12px'),
              borderRadius: stryMutAct_9fa48("1752") ? "" : (stryCov_9fa48("1752"), '12px'),
              height: stryMutAct_9fa48("1753") ? "" : (stryCov_9fa48("1753"), 'fit-content')
            })}>
                <Scale className="text-accent" size={24} />
              </div>
              <div>
                 <h2 className="text-primary font-bold mb-xs" style={stryMutAct_9fa48("1754") ? {} : (stryCov_9fa48("1754"), {
                fontSize: stryMutAct_9fa48("1755") ? "" : (stryCov_9fa48("1755"), '18px')
              })}>Institutional Usage</h2>
                 <p className="text-secondary" style={stryMutAct_9fa48("1756") ? {} : (stryCov_9fa48("1756"), {
                fontSize: stryMutAct_9fa48("1757") ? "" : (stryCov_9fa48("1757"), '14px'),
                lineHeight: 1.7
              })}>
                    FinGenie is provided as a financial utility for informational purposes. Analysis is generated by AI models and should be verified by certified professionals.
                 </p>
              </div>
           </div>

           <div className="d-flex gap-4">
              <div style={stryMutAct_9fa48("1758") ? {} : (stryCov_9fa48("1758"), {
              background: stryMutAct_9fa48("1759") ? "" : (stryCov_9fa48("1759"), 'rgba(235, 29, 72, 0.05)'),
              padding: stryMutAct_9fa48("1760") ? "" : (stryCov_9fa48("1760"), '12px'),
              borderRadius: stryMutAct_9fa48("1761") ? "" : (stryCov_9fa48("1761"), '12px'),
              height: stryMutAct_9fa48("1762") ? "" : (stryCov_9fa48("1762"), 'fit-content')
            })}>
                <AlertTriangle className="text-rose" size={24} style={stryMutAct_9fa48("1763") ? {} : (stryCov_9fa48("1763"), {
                color: stryMutAct_9fa48("1764") ? "" : (stryCov_9fa48("1764"), 'var(--accent-rose)')
              })} />
              </div>
              <div>
                 <h2 className="text-primary font-bold mb-xs" style={stryMutAct_9fa48("1765") ? {} : (stryCov_9fa48("1765"), {
                fontSize: stryMutAct_9fa48("1766") ? "" : (stryCov_9fa48("1766"), '18px')
              })}>No Financial Advice</h2>
                 <p className="text-secondary" style={stryMutAct_9fa48("1767") ? {} : (stryCov_9fa48("1767"), {
                fontSize: stryMutAct_9fa48("1768") ? "" : (stryCov_9fa48("1768"), '14px'),
                lineHeight: 1.7
              })}>
                    Output from FinGenie does not constitute financial, investment, or legal advice. FINGENIE FINANCIAL UTILITIES assumes no liability for decisions made based on AI output.
                 </p>
              </div>
           </div>
        </div>
      </div>
    </div>;
  }
}